### ISSUE TITLE
床宠物的文本存在问题

### ISSUE THREAD

**Issue by AlwaysReadyWBY** [SlimefunGuguProject/HotbarPets#10]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/HotbarPets/issues)，且没有找到相同的问题

### 问题描述

床宠物的描述中写着
喜欢的食物：原木
然而在查看了代码之后我发现实际上它所需的食物却是白色羊毛

### 复现步骤

1.在背包有原木的情况下使用床宠物，无法正常使用
2.在背包有羊毛的情况下使用床宠物，正常使用

### 预期行为

好烦啊这么简单的问题为什么要这么多格式烦死了烦死了烦死了烦死了烦死了

### 服务端软件

Paper

### Minecraft 版本

1.18.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

我受够了这些繁文缛节

### 插件版本

不知道，少烦我

**Comment by ybw0014** [comment]
不填完整的 issue 我可能会直接关闭。
已修复 [e0a233f](https://github.com/SlimefunGuguProject/HotbarPets/commit/e0a233f7060f0f04eed816b708f34d399141c668)
